# FILE: mkdocs.yml
site_name: 'Zen Practice Onboarding Plan'
site_description: 'A comprehensive 90-day guided journey into Zen meditation practice, designed with cultural respect and progressive skill building.'
site_url: 'https://example.com/zen-plan'
repo_url: 'https://github.com/example/zen-plan'
copyright: 'Copyright &copy; 2025 Zen Practice Plan'

theme:
    name: material
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - content.code.copy
        - content.action.edit
        - content.tabs.link
        - search.highlight
        - search.suggest
    palette:
        - scheme: default
          primary: teal
          accent: amber
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: teal
          accent: amber
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    icon:
        logo: material/meditation
        repo: fontawesome/brands/github
    font:
        text: 'Inter'
        code: 'JetBrains Mono'

plugins:
    - search
    - tags
    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.mark
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - def_list
    - attr_list
    - footnotes

extra:
    social:
        - icon: fontawesome/solid/book
          link: https://example.com
        - icon: fontawesome/brands/github
          link: https://github.com/example
    tags:
        enabled: true

extra_css:
    - stylesheets/extra.css

nav:
    - Home: index.md
    - Getting Started:
          - Welcome: getting-started/welcome.md
          - Safety & Wellbeing: getting-started/safety-wellbeing.md
          - How to Use This Plan: getting-started/how-to-use-this-plan.md
          - Glossary: getting-started/glossary.md
          - Posture & Breath: getting-started/posture-and-breath.md
          - Etiquette: getting-started/etiquette.md
          - Schools of Zen: getting-started/schools-of-zen.md
    - Foundations:
          - Core Practices: foundations/core-practices.md
          - Daily Structure Template: foundations/daily-structure-template.md
          - Habit Formation: foundations/habit-formation.md
          - Tracking Metrics: foundations/tracking-metrics.md
          - FAQ: foundations/frequently-asked-questions.md
    - Practice Plan:
          - Phases Overview: plan/phases-overview.md
          - Phase 1 - Orientation (Days 1-7): plan/phase-01-orientation-days-01-07.md
          - Phase 2 - Stabilization (Days 8-21): plan/phase-02-stabilization-days-08-21.md
          - Phase 3 - Deepening (Days 22-45): plan/phase-03-deepening-days-22-45.md
          - Phase 4 - Integration (Days 46-60): plan/phase-04-integration-days-46-60.md
          - Phase 5 - Expansion (Days 61-90): plan/phase-05-expansion-days-61-90.md
    - Daily Practices:
          - Days 1-30:
                - Day 1: days/day01.md
                - Day 2: days/day02.md
                - Day 3: days/day03.md
                - Day 4: days/day04.md
                - Day 5: days/day05.md
                - Day 6: days/day06.md
                - Day 7: days/day07.md
                - Day 8: days/day08.md
                - Day 9: days/day09.md
                - Day 10: days/day10.md
                - Day 11: days/day11.md
                - Day 12: days/day12.md
                - Day 13: days/day13.md
                - Day 14: days/day14.md
                - Day 15: days/day15.md
                - Day 16: days/day16.md
                - Day 17: days/day17.md
                - Day 18: days/day18.md
                - Day 19: days/day19.md
                - Day 20: days/day20.md
                - Day 21: days/day21.md
                - Day 22: days/day22.md
                - Day 23: days/day23.md
                - Day 24: days/day24.md
                - Day 25: days/day25.md
                - Day 26: days/day26.md
                - Day 27: days/day27.md
                - Day 28: days/day28.md
                - Day 29: days/day29.md
                - Day 30: days/day30.md
          - Days 31-60:
                - Day 31: days/day31.md
                - Day 32: days/day32.md
                - Day 33: days/day33.md
                - Day 34: days/day34.md
                - Day 35: days/day35.md
                - Day 36: days/day36.md
                - Day 37: days/day37.md
                - Day 38: days/day38.md
                - Day 39: days/day39.md
                - Day 40: days/day40.md
                - Day 41: days/day41.md
                - Day 42: days/day42.md
                - Day 43: days/day43.md
                - Day 44: days/day44.md
                - Day 45: days/day45.md
                - Day 46: days/day46.md
                - Day 47: days/day47.md
                - Day 48: days/day48.md
                - Day 49: days/day49.md
                - Day 50: days/day50.md
                - Day 51: days/day51.md
                - Day 52: days/day52.md
                - Day 53: days/day53.md
                - Day 54: days/day54.md
                - Day 55: days/day55.md
                - Day 56: days/day56.md
                - Day 57: days/day57.md
                - Day 58: days/day58.md
                - Day 59: days/day59.md
                - Day 60: days/day60.md
          - Days 61-90:
                - Day 61: days/day61.md
                - Day 62: days/day62.md
                - Day 63: days/day63.md
                - Day 64: days/day64.md
                - Day 65: days/day65.md
                - Day 66: days/day66.md
                - Day 67: days/day67.md
                - Day 68: days/day68.md
                - Day 69: days/day69.md
                - Day 70: days/day70.md
                - Day 71: days/day71.md
                - Day 72: days/day72.md
                - Day 73: days/day73.md
                - Day 74: days/day74.md
                - Day 75: days/day75.md
                - Day 76: days/day76.md
                - Day 77: days/day77.md
                - Day 78: days/day78.md
                - Day 79: days/day79.md
                - Day 80: days/day80.md
                - Day 81: days/day81.md
                - Day 82: days/day82.md
                - Day 83: days/day83.md
                - Day 84: days/day84.md
                - Day 85: days/day85.md
                - Day 86: days/day86.md
                - Day 87: days/day87.md
                - Day 88: days/day88.md
                - Day 89: days/day89.md
                - Day 90: days/day90.md
    - Reflection:
          - Weekly Reviews: reflection/weekly-reviews.md
          - Journaling Prompts: reflection/journaling-prompts.md
          - Obstacles & Adaptations: reflection/obstacles-and-adaptations.md
    - Enrichment:
          - Historical Context: enrichment/historical-context.md
          - Cultural Respect: enrichment/cultural-respect.md
          - Comparative Practices: enrichment/comparative-practices.md
          - Recommended Resources: enrichment/recommended-resources.md
          - Koan Primer: enrichment/koan-primer.md
    - Tags:
          - Tag Index: tag-index/index.md
    - Meta:
          - Roadmap: meta/roadmap.md
          - Methodology: meta/methodology.md
