site_name: 'Zen Practice Onboarding Plan'
site_description: 'A comprehensive 90-day guided journey into Zen meditation practice, designed with cultural respect and progressive skill building.'
site_url: 'https://sfboss.github.io/generated_plan_zen_ease_into_plan2/'
repo_url: 'https://github.com/sfboss/generated_plan_zen_ease_into_plan2'
repo_name: 'sfboss/generated_plan_zen_ease_into_plan2'
edit_uri: 'edit/main/docs/'
copyright: 'Copyright &copy; 2025 Zen Practice Onboarding Plan'

theme:
    name: material
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.indexes
        - content.code.copy
        - content.action.edit
        - content.tabs.link
        - search.highlight
        - search.suggest
        - search.share
        - toc.follow
        - toc.integrate
    palette:
        - scheme: default
          primary: deep orange
          accent: amber
          toggle:
              icon: material/weather-sunset
              name: Switch to dark mode
        - scheme: slate
          primary: deep orange
          accent: amber
          toggle:
              icon: material/weather-sunset-up
              name: Switch to light mode
    icon:
        logo: material/meditation
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/light-bulb-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16
    font:
        text: 'Inter'
        code: 'JetBrains Mono'
    favicon: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/material/assets/images/favicon.png

plugins:
    - search:
          separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - tags
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: true
    - macros:
          module_name: docs/macros
    - awesome-pages
    - git-revision-date-localized:
          type: timeago
          timezone: America/Los_Angeles
    - minify:
          minify_html: true
          minify_js: true
          minify_css: true

markdown_extensions:
    - admonition
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.mark
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.snippets
    - pymdownx.progressbar
    - def_list
    - attr_list
    - footnotes
    - md_in_html
    - tables

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/sfboss/generated_plan_zen_ease_into_plan2
          name: Source Repository
    tags:
        enabled: true

extra_css:
    - stylesheets/extra.css
    - stylesheets/zen-components.css
    - stylesheets/meditation-timer.css
    - stylesheets/progress-garden.css
    - stylesheets/breathing-guide.css

extra_javascript:
    - javascripts/zen-enhancements.js
    - javascripts/meditation-timer.js
    - javascripts/breathing-guide.js
    - javascripts/progress-tracking.js
    - javascripts/sound-effects.js
    - javascripts/ambient-sounds.js
    - javascripts/achievement-system.js
    - https://unpkg.com/mermaid/dist/mermaid.min.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Getting Started:
          - Welcome: getting-started/welcome.md
          - Safety & Wellbeing: getting-started/safety-wellbeing.md
          - How to Use This Plan: getting-started/how-to-use-this-plan.md
          - Posture & Breath: getting-started/posture-and-breath.md
          - Etiquette: getting-started/etiquette.md
          - Schools of Zen: getting-started/schools-of-zen.md
          - Glossary: getting-started/glossary.md
    - Foundations:
          - Core Practices: foundations/core-practices.md
          - FAQ: foundations/frequently-asked-questions.md
          - Habit Formation: foundations/habit-formation.md
    - Practice Plan:
          - Phases Overview: plan/phases-overview.md
          - Phase 1 - Orientation (Days 1-7): plan/phase-01-orientation-days-01-07.md
          - Phase 2 - Stabilization (Days 8-21): plan/phase-02-stabilization-days-08-21.md
          - Phase 3 - Deepening (Days 22-45): plan/phase-03-deepening-days-22-45.md
          - Phase 4 - Integration (Days 46-60): plan/phase-04-integration-days-46-60.md
          - Phase 5 - Expansion (Days 61-90): plan/phase-05-expansion-days-61-90.md
    - Daily Practices:
          - Day 1: days/day01.md
          - Day 2: days/day02.md
          - Day 3: days/day03.md
          - Day 4: days/day04.md
          - Day 5: days/day05.md
          - Day 6: days/day06.md
          - Day 7: days/day07.md
          - Day 8: days/day08.md
          - Day 9: days/day09.md
          - Day 10: days/day10.md
          - Day 11: days/day11.md
          - Day 12: days/day12.md
          - Day 13: days/day13.md
          - Day 14: days/day14.md
          - Day 15: days/day15.md
          - Day 16: days/day16.md
          - Day 17: days/day17.md
          - Day 18: days/day18.md
          - Day 19: days/day19.md
          - Day 20: days/day20.md
          - Day 21: days/day21.md
          - Day 22: days/day22.md
          - Day 30: days/day30.md
          - Day 45: days/day45.md
          - Day 60: days/day60.md
          - Day 75: days/day75.md
          - Day 90: days/day90.md
    - Progress Tracking:
          - Calendar View: progress/calendar-view.md
          - Progress Dashboard: progress/dashboard.md
          - Milestone Tracker: progress/milestones.md
    - Reflection:
          - Journaling Prompts: reflection/journaling-prompts.md
          - Weekly Reviews: reflection/weekly-reviews.md
    - Enrichment:
          - Cultural Respect: enrichment/cultural-respect.md
          - Historical Context: enrichment/historical-context.md
          - Recommended Resources: enrichment/recommended-resources.md
    - Tags: tag-index/index.md
