site_name: 'Zen Practice Onboarding Plan'
site_description: 'A comprehensive 90-day guided journey into Zen meditation practice, designed with cultural respect and progressive skill building.'
site_url: 'https://sfboss.github.io/generated_plan_zen_ease_into_plan2/'
repo_url: 'https://github.com/sfboss/generated_plan_zen_ease_into_plan2'
repo_name: 'sfboss/generated_plan_zen_ease_into_plan2'
edit_uri: 'edit/main/docs/'
copyright: 'Copyright &copy; 2025 Zen Practice Onboarding Plan'

theme:
    name: material
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.indexes
        - content.code.copy
        - content.action.edit
        - content.tabs.link
        - search.highlight
        - search.suggest
        - search.share
        - toc.follow
        - toc.integrate
    palette:
        - scheme: default
          primary: deep purple
          accent: teal
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: deep purple
          accent: teal
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    icon:
        logo: material/meditation
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
    font:
        text: 'Inter'
        code: 'JetBrains Mono'
    favicon: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/material/assets/images/favicon.png

plugins:
    - search:
          separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - tags:
          tags_file: tag-index/index.md
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: true
    - blog:
          blog_dir: reflection/blog
          blog_toc: true
          post_dir: '{blog}/posts'
          post_date_format: full
          post_url_date_format: yyyy/MM/dd
          post_url_format: '{date}/{slug}'
          post_excerpt: optional
          post_excerpt_max_authors: 2
          post_excerpt_max_categories: 5
          post_readtime: true
          post_readtime_words_per_minute: 265
          pagination: true
          pagination_per_page: 10
          pagination_url_format: 'page/{page}'
          pagination_format: '~2~'
          pagination_if_single_page: false
          pagination_keep_content: false
          authors: true
          authors_file: '{blog}/.authors.yml'
          categories: true
          categories_name: 'Categories'
          categories_url_format: 'category/{slug}'
          categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
              kwds:
                  case: lower
          categories_slugify_separator: '-'
          categories_allowed:
              - weekly-review
              - insights
              - challenges
              - milestones
              - practice-tips
          archive: true
          archive_name: 'Archive'
          archive_date_format: '%Y'
          archive_url_date_format: yyyy
          archive_url_format: '{date}'
          archive_toc: true

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.mark
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - def_list
    - attr_list
    - footnotes

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/sfboss/generated_plan_zen_ease_into_plan2
          name: Source Repository
    tags:
        enabled: true

extra_css:
    - stylesheets/extra.css

nav:
    - Home: index.md
    - Getting Started:
          - Welcome: getting-started/welcome.md
          - Safety & Wellbeing: getting-started/safety-wellbeing.md
          - How to Use This Plan: getting-started/how-to-use-this-plan.md
          - Posture & Breath: getting-started/posture-and-breath.md
          - Etiquette: getting-started/etiquette.md
          - Schools of Zen: getting-started/schools-of-zen.md
          - Glossary: getting-started/glossary.md
    - Foundations:
          - Core Practices: foundations/core-practices.md
          - FAQ: foundations/frequently-asked-questions.md
    - Practice Plan:
          - Phases Overview: plan/phases-overview.md
          - Phase 2 - Stabilization (Days 8-21): plan/phase-02-stabilization-days-08-21.md
    - Daily Practices:
          - Week 1 (Days 1-7):
                - Day 1: days/day01.md
                - Day 2: days/day02.md
                - Day 3: days/day03.md
                - Day 7: days/day07.md
          - Week 2-3 (Days 8-21):
                - Day 8: days/day08.md
                - Day 15: days/day15.md
          - Week 4+ (Days 22-90):
                - Day 22: days/day22.md
                - Day 30: days/day30.md
                - Day 45: days/day45.md
                - Day 60: days/day60.md
                - Day 75: days/day75.md
                - Day 90: days/day90.md
    - Progress Tracking:
          - Calendar View: progress/calendar-view.md
          - Progress Dashboard: progress/dashboard.md
          - Milestone Tracker: progress/milestones.md
    - Reflection:
          - Blog: reflection/blog/index.md
          - Weekly Reviews: reflection/weekly-reviews.md
    - Enrichment:
          - Cultural Respect: enrichment/cultural-respect.md
    - Tags: tag-index/index.md
